default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: beer_development
  
test:
  <<: *default
  database: beer_test

# production:
#   <<: *default
#   database: db/production.sqlite3
